# config-cluster.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-cluster
servers: 1
agents: 2
kubeAPI:
  host: "0.0.0.0"
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  # Original ports
  - port: 9080:80
    nodeFilters:
      - loadbalancer
  - port: 9443:443
    nodeFilters:
      - loadbalancer
  # MinIO ports
  - port: 30900:30900
    nodeFilters:
      - loadbalancer
  - port: 30901:30901
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${HOME}/k3d/data/minio:/mnt/minio
    nodeFilters:
      - all
options:
  k3d:
    wait: true
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*