deployment:
  enabled: true
  replicas: 1

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    port: 80
    expose: 
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
  postgres:
    port: 5432
    expose: 
      default: true
    exposedPort: 5432
    protocol: TCP

api:
  dashboard: true
  insecure: true

dashboard:
  enabled: true

service:
  enabled: true
  type: LoadBalancer

additionalArguments:
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.postgres.address=:5432/tcp"
  - "--providers.kubernetesingress.allowexternalnameservices=true"
  - "--log.level=DEBUG"