prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: minio
        static_configs:
          - targets: 
            - "minio:30901"
      - job_name: clickhouse
        static_configs:
          - targets:
            - "clickhouse:30123"