# clickhouse-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: database
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 30123
    - name: native
      port: 9000
      targetPort: 9000
      nodePort: 30910
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: clickhouse
  type: NodePort