# clickhouse-full.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-data-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/clickhouse/data-0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-data-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/clickhouse/data-1
  persistentVolumeReclaimPolicy: Retain
---
# clickhouse-instance.yaml
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse
  namespace: database
spec:
  configuration:
    clusters:
      - name: cluster
        layout:
          shardsCount: 1
          replicasCount: 1
    users:
      default/password: clickhouse  # clickhouse
      default/networks/ip: "::/0"
      default/profile: default
      default/quota: default
      default/access_management: 1
      admin/password: admin_password  # admin_password
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/quota: default
      admin/access_management: 1
    profiles:
      default/max_memory_usage: 10000000000
    # settings:
    #   allow_experimental_database_materialized_mysql: 1
    files:
      users.xml: |-
        <clickhouse>
          <users>
            <default>
              <password>clickhouse</password>
              <networks><ip>::/0</ip></networks>
              <profile>default</profile>
              <quota>default</quota>
              <access_management>1</access_management>
            </default>
            <admin>
              <password>admin_password</password>
              <networks><ip>::/0</ip></networks>
              <profile>default</profile>
              <quota>default</quota>
              <access_management>1</access_management>
            </admin>
          </users>
          <quotas>
            <default>
              <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
              </interval>
            </default>
          </quotas>
          <profiles>
            <default>
              <max_memory_usage>10000000000</max_memory_usage>
              <use_uncompressed_cache>0</use_uncompressed_cache>
              <load_balancing>random</load_balancing>
            </default>
          </profiles>
        </clickhouse>
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.8
              ports:
                - name: http
                  containerPort: 8123
                - name: native
                  containerPort: 9000
              volumeMounts:
                - name: data-volume-template
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: 1Gi
                  cpu: "0.5"
                limits:
                  memory: 2Gi
                  cpu: "1"
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: local-path
  defaults:
    templates:
      podTemplate: clickhouse-pod-template
      dataVolumeClaimTemplate: data-volume-template