apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: database
spec:
  ports:
    - port: 9092
      name: internal
      targetPort: 9092
      nodePort: 30092
  selector:
    app: kafka
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: database
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.5.1
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 30092
              name: external
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9092,EXTERNAL://:30092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service.database.svc.cluster.local:9092,EXTERNAL://127.0.0.1:30092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"