apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: database
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: database
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.7.0
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: "server.1=0.0.0.0:2888:3888;2181"
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "*"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
            - name: zookeeper-datalog
              mountPath: /datalog
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /mnt/zookeeper/data
            type: DirectoryOrCreate
        - name: zookeeper-datalog
          hostPath:
            path: /mnt/zookeeper/datalog
            type: DirectoryOrCreate