apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airflow
  namespace: airflow
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`airflow.localhost`)
      kind: Rule
      services:
        - name: airflow-webserver
          port: 8080